---

- hosts: all
  become: true
  tasks:

    - name: update all packages
      apt:
        update_cache: yes
        upgrade: dist
      when: ansible_os_family == 'Debian'

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == 'RedHat'

- import_playbook: bigbluebutton.yml
